name: IaC tag and trace

on:
  push:
  pull_request:

permissions:
  contents: write
  actions: write
  pull-requests: write
  
jobs:
  yor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
        with:
          fetch-depth: 0
      - name: Run yor action
        uses: bridgecrewio/yor-action@main
